# Maintained recipe 1: pinned release source, toolchain and readonly module graph.
FROM golang:1.26.6-alpine3.24@sha256:3889b425f035be855a72fb4755265311293b6d414521f0a519d819df32222d83 AS build
WORKDIR /src
ENV CGO_ENABLED=0 GOTOOLCHAIN=local GOENV=off GOWORK=off GOPROXY=https://proxy.golang.org GOSUMDB=sum.golang.org GOFLAGS=-mod=readonly GOTELEMETRY=off
RUN test "$(go version | cut -d ' ' -f 3)" = go1.26.6 \
    && wget -O /tmp/source.tar.gz https://codeload.github.com/tianon/gosu/tar.gz/6456aaa0f3c854d199d0f037f068eb97515b7513 \
    && echo '33d7537d588ea49458b9509bcf4554bdf5ceacc66da71e5caa1058ea3b689c3b  /tmp/source.tar.gz' | sha256sum -c - \
    && tar -xzf /tmp/source.tar.gz --strip-components=1 -C /src \
    && rm /tmp/source.tar.gz
COPY requirements/service-builds/gosu/go.mod requirements/service-builds/gosu/go.sum ./
COPY requirements/service-builds/gosu/modules.txt /locked-modules.txt
RUN printf '%s\n' '0475f1708db81d718b633faf2d9dd64695037eabdc8562125060607bcb01b2ba  go.mod' '2a8f3fb6adb84839bbb9999f12f1416fb86c184135aaa1c2e489b35203c08346  go.sum' 'b70689176f6f20583005676536c5bb86b46a5249499fdf9bdf6920728b89ed6a  /locked-modules.txt' | sha256sum -c - \
    && go mod download \
    && go mod verify \
    && go list -m all | cmp - /locked-modules.txt \
    && mkdir /out \
    && go build -trimpath -buildvcs=false -ldflags='-s -w' -o /out/gosu . \
    && cp /locked-modules.txt /out/GO-MODULES.txt \
    && find /go/pkg/mod -type f \( -iname 'license*' -o -iname 'notice*' -o -iname 'copying*' -o -iname 'copyright*' \) \
       -exec sh -c 'for p do printf "\nSOURCE LICENSE %s\n" "$p"; cat "$p"; done' sh {} + > /out/THIRD-PARTY-NOTICES.txt
FROM postgres:16.15-alpine3.24@sha256:721873c34ceb9f8d8fc265984940dc982404c105f19ad51be9fdc5970a6080ea
COPY --from=build /out/gosu /usr/local/bin/gosu
COPY --from=build /src/LICENSE /usr/local/share/licenses/shadai/gosu/LICENSE
COPY --from=build /usr/local/go/LICENSE /usr/local/share/licenses/shadai/gosu/GO-LICENSE
COPY --from=build /out/GO-MODULES.txt /out/THIRD-PARTY-NOTICES.txt /usr/local/share/licenses/shadai/gosu/
LABEL io.shadai.maintenance.recipe="1" \
      io.shadai.maintenance.component="gosu" \
      io.shadai.maintenance.version="1.19-shadai.1" \
      io.shadai.maintenance.source="6456aaa0f3c854d199d0f037f068eb97515b7513" \
      io.shadai.maintenance.toolchain="go1.26.6"
RUN gosu --version | grep -F "1.19 (go1.26.6 " && test "$(gosu nobody id -u)" = 65534
