import { useState } from 'react'
import { useQuery } from '@tanstack/react-query'
import { Search, BookOpen } from 'lucide-react'
import client from '@/api/client'
import type { CatalogItem } from '@/types'
import ErrorAlert from '@/components/ui/ErrorAlert'
import EmptyState from '@/components/ui/EmptyState'
import { TableSkeleton } from '@/components/ui/LoadingSkeleton'
export default function Catalog() {
  const [search, setSearch] = useState('')
  const query = useQuery({ queryKey: ['catalog',search], queryFn: () => client.get<CatalogItem[]>(`/catalog?page_size=100&search=${encodeURIComponent(search)}`).then(r=>({ items:r.data,total:r.headers['x-total-count'] ? Number(r.headers['x-total-count']) : null })) })
  return <div className="space-y-5"><div><p className="eyebrow mb-2">Detection knowledge</p><h1 className="page-heading">AI catalog</h1><p className="page-description">Known service identifiers used to match incoming evidence. Catalog entries are not proof of organizational use.</p></div><div className="relative max-w-md"><Search size={16} className="absolute left-3 top-3 text-slate-500"/><input className="field w-full !pl-10" aria-label="Search catalog" placeholder="Search the catalog…" value={search} onChange={e=>setSearch(e.target.value)}/></div>{query.isError ? <ErrorAlert onRetry={query.refetch}/> : query.isPending ? <TableSkeleton rows={6} columns={5}/> : !query.data.items.length ? <EmptyState icon={BookOpen} title="No catalog entries found" description="Adjust your search or import the community catalog during deployment."/> : <><p className="text-xs text-slate-500">Showing {query.data.items.length}{query.data.total!==null ? ` of ${query.data.total}` : ' entries (up to 100)'} matching entries.</p><div className="stat-card !p-0 overflow-x-auto"><table className="w-full text-sm"><thead className="text-left text-[10px] uppercase tracking-wider text-slate-500"><tr>{['Name', 'Category', 'Vendor', 'Identifiers', 'Source', 'Status'].map(name=><th key={name} className="px-4 py-3">{name}</th>)}</tr></thead><tbody>{query.data.items.map(item=><tr key={item.catalog_item_id} className="data-row"><td className="px-4 py-4 font-medium">{item.canonical_name}</td><td className="px-4 py-4 text-xs text-slate-400">{item.category.replaceAll('_',' ')}</td><td className="px-4 py-4 text-xs text-slate-400">{item.vendor || '—'}</td><td className="px-4 py-4 text-xs font-mono text-slate-400 max-w-xs truncate" title={[...(item.domains||[]), ...(item.processes||[])].join(', ')}>{[...(item.domains||[]), ...(item.processes||[])].slice(0,2).join(', ') || 'Other identifiers'}</td><td className="px-4 py-4 text-xs text-slate-400">{item.source_of_truth}</td><td className="px-4 py-4"><span className="badge bg-surface-700 text-slate-300">{item.status}</span></td></tr>)}</tbody></table></div></>}</div>
}
