import { useI18n } from '@/i18n'
import { useQuery, useQueryClient } from '@tanstack/react-query'
import { Link } from 'react-router-dom'
import { AreaChart, Area, XAxis, YAxis, Tooltip, ResponsiveContainer, CartesianGrid } from 'recharts'
import { ArrowRight, ArrowUpRight, Search, ShieldAlert, CircleDot, Layers3, RefreshCw, Database, Info } from 'lucide-react'
import { getSummary, getTrend, getSourceHealth, getEvidence } from '@/api/dashboard'
import { listDetections } from '@/api/detections'
import RiskBadge from '@/components/badges/RiskBadge'
import ClassificationBadge from '@/components/badges/ClassificationBadge'
import ErrorAlert from '@/components/ui/ErrorAlert'
import { CardsSkeleton } from '@/components/ui/LoadingSkeleton'

export default function Dashboard() {
  const { tr, textLabel, enumLabel, formatDate, formatNumber } = useI18n()

  const cache = useQueryClient()
  const summary = useQuery({ queryKey: ['summary'], queryFn: getSummary })
  const trend = useQuery({ queryKey: ['trend'], queryFn: () => getTrend(30) })
  const sources = useQuery({ queryKey: ['source-health'], queryFn: getSourceHealth })
  const evidence = useQuery({ queryKey: ['evidence'], queryFn: getEvidence })
  const queue = useQuery({ queryKey: ['priority-detections'], queryFn: () => listDetections({ analyst_status: 'new', page_size: 10, sort_by: 'risk_score', sort_order: 'desc' }) })
  const stats = summary.data
  const ev = evidence.data
  const known = ev ? ev.measurement.model_known_events : 0
  const coverage = ev?.total_events ? Math.round(known / ev.total_events * 100) : 0
  const cards = stats ? [
    { label: 'Tools discovered', value: stats.total, detail: 'All retained detections', icon: Search, to: '/discoveries', color: 'text-accent' },
    { label: 'Unsanctioned', value: stats.unsanctioned, detail: 'Organizational classification', icon: ShieldAlert, to: '/discoveries?classification=unsanctioned', color: 'text-rose-300' },
    { label: 'High & critical risk', value: stats.high_risk, detail: 'Last computed scores', icon: Layers3, to: '/discoveries?risk_level=critical,high', color: 'text-amber-300' },
    { label: 'Awaiting review', value: stats.unreviewed, detail: 'New findings in your queue', icon: CircleDot, to: '/discoveries?analyst_status=new', color: 'text-accent' },
  ] : []
  return <div className="space-y-7">
    <div className="flex flex-wrap items-center justify-between gap-4"><div><p className="eyebrow mb-2">{tr("Your AI landscape")}</p><h1 className="page-heading">{tr("Evidence into oversight.")}</h1><p className="page-description">{tr("Understand observed AI activity. Focus on what needs a decision.")}</p></div><div className="flex gap-2"><button className="secondary-button" onClick={()=>cache.invalidateQueries()} aria-label={tr("Refresh workspace")}><RefreshCw size={14}/><span className="hidden sm:inline">{tr("Refresh")}</span></button><Link to="/discoveries?analyst_status=new" className="primary-button">{tr("Review discoveries")} <ArrowRight size={15}/></Link></div></div>
    {summary.isError ? <ErrorAlert message={tr("Overview counts are unavailable.")} onRetry={summary.refetch}/> : !stats ? <CardsSkeleton count={4}/> : <div className="grid grid-cols-2 xl:grid-cols-4 gap-3 md:gap-4">{cards.map(card=><Link to={card.to} key={textLabel(card.label)} className="stat-card group relative hover:border-accent/40 transition-colors"><div className="flex justify-between items-center mb-5"><p className="text-xs text-slate-400">{textLabel(card.label)}</p><card.icon size={16} className={card.color}/></div><div className="flex items-end justify-between"><p className="text-[38px] font-medium leading-none tracking-[-.05em] tabular-nums">{formatNumber(card.value)}</p><ArrowUpRight size={15} className="text-slate-500 group-hover:text-accent"/></div><p className="text-[10px] text-slate-500 mt-3">{textLabel(card.detail)}</p></Link>)}</div>}
    <div className="grid xl:grid-cols-[minmax(0,1.9fr)_minmax(290px,1fr)] gap-5">
      <section className="stat-card"><div className="flex justify-between items-start gap-3"><div><h2 className="font-medium text-sm">{tr("Discovery activity")}</h2><p className="text-xs text-slate-500 mt-1">{tr("New detections first observed each day")}</p></div><span className="text-[10px] rounded-md border border-surface-600/50 px-2 py-1 text-slate-400">{tr("Last 30 days")}</span></div><div className="h-[220px] mt-6" role="img" aria-label={tr('Discovery trend over 30 days. {count} new detections.', { count: trend.data ? formatNumber(trend.data.reduce((sum, row) => sum + row.count, 0)) : tr('Unavailable') })}>{trend.isError ? <ErrorAlert message={tr("Trend unavailable")} onRetry={trend.refetch}/> : trend.isPending ? <p className="text-sm text-slate-500">{tr("Loading activity…")}</p> : !trend.data?.length ? <p className="text-sm text-slate-500">{tr("No discoveries in this period.")}</p> : <ResponsiveContainer width="100%" height="100%"><AreaChart data={trend.data} margin={{ top: 8, right: 8, left: -25, bottom: 0 }}><defs><linearGradient id="activity-fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#65dbc6" stopOpacity={.22}/><stop offset="100%" stopColor="#65dbc6" stopOpacity={.01}/></linearGradient></defs><CartesianGrid vertical={false} stroke="#26343e" strokeDasharray="3 5"/><XAxis dataKey="date" tick={{ fontSize: 10, fill: '#92a0ac' }} axisLine={false} tickLine={false} minTickGap={32} tickFormatter={v=>formatDate(v, { month: 'short', day: 'numeric' })}/><YAxis tick={{ fontSize: 10, fill: '#92a0ac' }} tickLine={false} axisLine={false} allowDecimals={false} tickFormatter={value => formatNumber(Number(value))}/><Tooltip contentStyle={{ background: '#162129', border: '1px solid #3c4d57', borderRadius: 8, fontSize: 12 }} labelFormatter={v=>formatDate(String(v), { dateStyle: 'medium' })} formatter={value => formatNumber(Number(value))}/><Area type="monotone" dataKey="count" name={tr("New detections")} stroke="#65dbc6" strokeWidth={2} fill="url(#activity-fill)" isAnimationActive={false}/></AreaChart></ResponsiveContainer>}</div></section>
      <section className="stat-card"><div className="flex items-center justify-between"><h2 className="text-sm font-medium">{tr("Evidence coverage")}</h2><Info size={15} className="text-slate-500"/></div><p className="text-xs text-slate-500 mt-1">{tr("Source-reported model · last 30 days")}</p>{evidence.isError ? <ErrorAlert message={tr("Evidence metrics unavailable")} onRetry={evidence.refetch}/> : !ev ? <p className="text-sm text-slate-500 mt-7">{tr("Loading evidence…")}</p> : <><div className="flex items-baseline gap-2 mt-7"><span className="text-[42px] leading-none font-medium tracking-tight">{coverage}<span className="text-2xl text-slate-400">%</span></span><span className="text-xs text-slate-400">{tr("of observed events")}</span></div><div className="h-2 bg-surface-700 rounded-full overflow-hidden mt-5"><div className="h-full bg-accent rounded-full" style={{ width: `${Math.min(100, coverage)}%` }}/></div><div className="flex justify-between text-[10px] text-slate-500 mt-2"><span>{tr('{count} model reported', { count: formatNumber(known) })}</span><span>{tr('{count} unknown', { count: formatNumber(ev.total_events-known) })}</span></div><div className="border-t border-surface-600/30 mt-5 pt-4 flex items-start gap-2"><Info size={14} className="text-accent shrink-0 mt-0.5"/><p className="text-xs leading-relaxed text-slate-400">{tr("A domain match identifies a service. Model names, prompts, tokens and cost require explicit evidence.")}</p></div></>}</section>
    </div>
    <section className="stat-card p-0! overflow-hidden"><div className="flex justify-between items-center gap-4 p-5"><div className="flex gap-3 items-center"><span className="w-8 h-8 rounded-lg bg-amber-500/10 flex items-center justify-center"><ShieldAlert className="text-amber-300" size={16}/></span><div><h2 className="text-sm font-medium">{tr("Your review queue")}</h2><p className="text-xs text-slate-500 mt-1">{tr("Last computed risk · new findings")}</p></div></div><Link to="/discoveries?analyst_status=new" className="text-xs text-accent flex items-center gap-2">{tr("View all")} <ArrowRight size={13}/></Link></div>{queue.isError ? <ErrorAlert message={tr("Review queue unavailable")} onRetry={queue.refetch}/> : queue.isPending ? <p className="p-5 text-sm text-slate-500">{tr("Loading review queue…")}</p> : !queue.data?.items.length ? <p className="px-5 pb-7 text-sm text-slate-400">{tr("No new findings to review. Coverage depends on connected sources.")}</p> : <div className="overflow-x-auto"><table className="w-full text-sm"><thead className="text-left text-[10px] uppercase tracking-[.1em] text-slate-500 bg-surface-950/40"><tr><th className="px-5 py-3 font-medium">{tr("AI tool / service")}</th><th className="px-5 py-3 font-medium">{tr("Evidence source")}</th><th className="px-5 py-3 font-medium">{tr("Classification")}</th><th className="px-5 py-3 font-medium">{tr("Risk")}</th><th className="px-5 py-3 font-medium text-right">{tr("Events")}</th><th className="px-5 py-3"><span className="sr-only">{tr("Review")}</span></th></tr></thead><tbody>{queue.data.items.slice(0,5).map(d=><tr key={d.detection_id} className="data-row"><td className="px-5 py-4"><Link to={`/discoveries/${d.detection_id}`} className="font-medium hover:text-accent">{d.entity_name}</Link><span className="block text-[10px] text-slate-500 mt-1">{enumLabel(d.entity_type)}</span></td><td className="px-5 py-4 text-xs text-slate-400">{d.source_types.map(enumLabel).join(' + ')}</td><td className="px-5 py-4"><ClassificationBadge classification={d.classification}/></td><td className="px-5 py-4"><RiskBadge stale={d.risk_score_stale} level={d.risk_level} score={d.risk_score} showScore/></td><td className="px-5 py-4 text-xs font-mono text-right text-slate-400">{formatNumber(d.total_events_count)}</td><td className="px-5 py-4"><Link to={`/discoveries/${d.detection_id}`} aria-label={tr("Review {name}", { name: d.entity_name })} className="text-slate-500 hover:text-accent"><ArrowUpRight size={16}/></Link></td></tr>)}</tbody></table></div>}</section>
    <div className="grid xl:grid-cols-2 gap-5"><section className="stat-card"><div className="flex justify-between items-center mb-5"><div><h2 className="text-sm font-medium">{tr("Source health")}</h2><p className="text-xs text-slate-500 mt-1">{tr("Activity indicates ingestion, not complete coverage")}</p></div><Link to="/sources" className="text-accent text-xs">{tr("Details")} <ArrowUpRight size={13} className="inline"/></Link></div>{sources.isError ? <ErrorAlert onRetry={sources.refetch}/> : !sources.data?.length ? <p className="text-xs text-slate-500">{sources.isPending ? tr("Checking sources…") : tr("No source observations available.")}</p> : <div className="grid sm:grid-cols-2 gap-2">{sources.data.map(source=><div key={enumLabel(source.source_type)} className="flex items-center justify-between rounded-lg border border-surface-600/25 px-3 py-3"><span className="flex gap-2 text-xs text-slate-300"><Database size={13} className="text-slate-500"/>{enumLabel(source.source_type)}</span><span className={`text-[10px] flex items-center gap-1.5 ${source.status === 'active' ? 'text-accent' : source.status === 'warning' ? 'text-amber-300' : 'text-slate-500'}`}><span className="w-1.5 h-1.5 rounded-full bg-current"/>{source.status === 'inactive' && !source.last_event ? tr("No data") : enumLabel(source.status)}</span></div>)}</div>}</section><section className="stat-card"><h2 className="text-sm font-medium">{tr("Measured, not inferred")}</h2><p className="text-xs text-slate-500 mt-1">{tr("Explicitly reported telemetry · last 30 days")}</p>{evidence.isError ? <ErrorAlert onRetry={evidence.refetch}/> : !ev ? <p className="mt-5 text-xs text-slate-500">{tr("Loading measurements…")}</p> : <><div className="grid grid-cols-3 divide-x divide-surface-600/30 mt-6"><div><p className="text-2xl font-medium tabular-nums">{formatNumber(ev.total_events)}</p><p className="text-[10px] text-slate-500 mt-2">{tr("Observed events")}</p></div><div className="pl-4"><p className="text-2xl font-medium tabular-nums">{ev.measurement.input_tokens === null || ev.measurement.output_tokens === null ? '—' : formatNumber((ev.measurement.input_tokens+ev.measurement.output_tokens))}</p><p className="text-[10px] text-slate-500 mt-2">{tr("Reported tokens")}</p></div><div className="pl-4"><p className="text-2xl font-medium tabular-nums">{ev.measurement.cost_usd === null ? '—' : formatNumber(ev.measurement.cost_usd, { style: 'currency', currency: 'USD' })}</p><p className="text-[10px] text-slate-500 mt-2">{tr("Reported cost")}</p></div></div><p className="text-xs text-slate-500 leading-relaxed border-t border-surface-600/30 pt-4 mt-5">{tr('Token data covers {reported} of {total} events. Missing measurements are unknown. This console does not block requests or inspect prompt content by default.', { reported: formatNumber(ev.measurement.tokens_reported_events), total: formatNumber(ev.total_events) })}</p></>}</section></div>
    {ev && ev.models.length > 0 && <section className="stat-card"><div className="mb-4"><h2 className="text-sm font-medium">{tr("Source-reported models")}</h2><p className="text-xs text-slate-500 mt-1">{tr("Names supplied by observed telemetry, not independently verified model provenance.")}</p></div><div className="overflow-x-auto"><table className="w-full text-xs"><thead className="text-left text-slate-500"><tr><th className="py-2 pr-5">{tr("Provider")}</th><th className="py-2 pr-5">{tr("Reported model")}</th><th className="py-2 pr-5">{tr("Provenance")}</th><th className="py-2 text-right">{tr("Events")}</th></tr></thead><tbody>{ev.models.map((model,i)=><tr key={`${model.provider}-${model.model}-${i}`} className="data-row"><td className="py-3 pr-5">{model.provider || tr("Unknown")}</td><td className="py-3 pr-5 font-mono text-accent">{model.model}</td><td className="py-3 pr-5 text-slate-400">{enumLabel(model.model_provenance)}</td><td className="py-3 text-right font-mono">{formatNumber(model.events)}</td></tr>)}</tbody></table></div></section>}<p className="text-[10px] text-slate-500">{tr("Detection totals cover retained records. Evidence and measurement metrics cover the last 30 days. Scores prioritize review; they do not establish data disclosure.")}</p>
  </div>
}
