import { useI18n } from '@/i18n'
import { useQuery } from '@tanstack/react-query'
import { Database, Info, ArrowUpRight, Network } from 'lucide-react'
import { Link } from 'react-router-dom'
import { getSourceHealth } from '@/api/dashboard'
import ErrorAlert from '@/components/ui/ErrorAlert'
import { CardsSkeleton } from '@/components/ui/LoadingSkeleton'
import { useAuthStore } from '@/stores/auth'
import CollectorOperations from '@/components/sources/CollectorOperations'
const limitations: Record<string,string> = { network: 'Passive DNS, TLS, QUIC and HTTP metadata from configured sensors. These protocols are one evidence source. A lookup or connection is not proof of AI use, a user identity, a model or token counts.', dns: 'Domain resolution only. Does not establish use, model identity, prompts, or tokens.', proxy: 'Requests to known services. Model identity requires explicit metadata.', endpoint: 'Managed-device inventory and local runtime signals. Unmanaged devices remain outside coverage.', browser: 'Browser extension inventory. Installation does not establish active use.', oauth: 'Application grants and permissions. A grant does not establish actual data access.', directory: 'Identity context for correlation, subject to source scope.', instrumented: 'Explicit application metadata; token and cost fields may still be missing.', casb: 'Visibility depends on upstream CASB coverage and event detail.' }
export default function Sources() {
  const { tr, textLabel, enumLabel, formatDate, formatNumber } = useI18n()

  const mode = useAuthStore(state => state.mode)
  const session = useAuthStore(state => state.session)
  const role = useAuthStore(state => state.user?.role)
  const query = useQuery({ queryKey: ['source-health', mode, session], queryFn: getSourceHealth, refetchInterval: 60_000 })
  return <div className="space-y-6"><div><p className="eyebrow mb-2">{tr("Understand your visibility")}</p><h1 className="page-heading">{tr("Sources & coverage")}</h1><p className="page-description">{tr("Observed ingestion health, with the limits of each evidence source.")}</p></div><CollectorOperations key={`${mode}-${session}-${role}`}/><div className="flex gap-3 p-4 rounded-xl border border-accent/20 bg-accent/5 text-xs text-slate-300 leading-relaxed"><Info size={16} className="text-accent shrink-0"/><p>{tr("Active means recent events were received. Inactive sources and missing measurements represent unknown coverage. Configure ingestion in your deployment, then verify incoming events here.")}</p></div>{query.isError ? <ErrorAlert message={tr("Source health is unavailable.")} onRetry={query.refetch}/> : query.isPending ? <CardsSkeleton count={4}/> : !query.data.length ? <div className="stat-card text-sm text-slate-400">{tr("No source observations yet. Review the deployment guide to connect your first source.")}</div> : <div className="grid md:grid-cols-2 xl:grid-cols-3 gap-4">{query.data.map(source => {
    const Icon = source.source_type === 'network' ? Network : Database
    return <section key={source.source_type} className="stat-card"><div className="flex items-center justify-between mb-5"><span className="flex items-center gap-2 font-medium capitalize text-sm"><Icon size={17} className="text-accent"/>{enumLabel(source.source_type)}</span><span className={`badge ${source.status==='active' ? 'bg-accent/10 text-accent' : source.status==='warning' ? 'bg-amber-500/10 text-amber-300' : 'bg-surface-700 text-slate-400'}`}>{!source.last_event ? tr("No data") : enumLabel(source.status)}</span></div><dl className="text-xs space-y-3"><div className="flex justify-between"><dt className="text-slate-500">{tr("Events per minute")}</dt><dd className="font-mono">{formatNumber(source.events_per_minute)}</dd></div><div className="flex justify-between gap-2"><dt className="text-slate-500 shrink-0">{tr("Last event")}</dt><dd className="text-right">{source.last_event ? formatDate(source.last_event) : tr("Not observed")}</dd></div></dl><p className="border-t border-surface-600/30 mt-5 pt-4 text-xs text-slate-400 leading-relaxed">{textLabel(limitations[source.source_type] || tr("Source-specific visibility depends on the connected upstream system."))}</p>{source.source_type === 'network' && <Link to="/network" className="inline-flex text-xs text-accent mt-4">{tr("Inspect network observations")}</Link>}</section>
  })}</div>}<a className="secondary-button" href="https://github.com/alebgl77/open-shadow-ai#quick-start" target="_blank" rel="noreferrer">{tr("Deployment & ingestion guide")}<ArrowUpRight size={14}/></a></div>
}
