import { useQuery } from '@tanstack/react-query'
import { Database, Info, ArrowUpRight, Network } from 'lucide-react'
import { Link } from 'react-router-dom'
import { getSourceHealth } from '@/api/dashboard'
import ErrorAlert from '@/components/ui/ErrorAlert'
import { CardsSkeleton } from '@/components/ui/LoadingSkeleton'
import { sourceLabel } from '@/components/ui/SourceIcons'
import { useAuthStore } from '@/stores/auth'
const limitations: Record<string,string> = { network: 'Passive DNS, TLS, QUIC and HTTP metadata from configured sensors. These protocols are one evidence source. A lookup or connection is not proof of AI use, a user identity, a model or token counts.', dns: 'Domain resolution only. Does not establish use, model identity, prompts, or tokens.', proxy: 'Requests to known services. Model identity requires explicit metadata.', endpoint: 'Managed-device inventory and local runtime signals. Unmanaged devices remain outside coverage.', browser: 'Browser extension inventory. Installation does not establish active use.', oauth: 'Application grants and permissions. A grant does not establish actual data access.', directory: 'Identity context for correlation, subject to source scope.', instrumented: 'Explicit application metadata; token and cost fields may still be missing.', casb: 'Visibility depends on upstream CASB coverage and event detail.' }
export default function Sources() {
  const mode = useAuthStore(state => state.mode)
  const session = useAuthStore(state => state.session)
  const query = useQuery({ queryKey: ['source-health', mode, session], queryFn: getSourceHealth, refetchInterval: 60_000 })
  return <div className="space-y-6"><div><p className="eyebrow mb-2">Understand your visibility</p><h1 className="page-heading">Sources & coverage</h1><p className="page-description">Observed ingestion health, with the limits of each evidence source.</p></div><div className="flex gap-3 p-4 rounded-xl border border-accent/20 bg-accent/5 text-xs text-slate-300 leading-relaxed"><Info size={16} className="text-accent shrink-0"/><p>Active means recent events were received. Inactive sources and missing measurements represent unknown coverage. Configure ingestion in your deployment, then verify incoming events here.</p></div>{query.isError ? <ErrorAlert message="Source health is unavailable." onRetry={query.refetch}/> : query.isPending ? <CardsSkeleton count={4}/> : !query.data.length ? <div className="stat-card text-sm text-slate-400">No source observations yet. Review the deployment guide to connect your first source.</div> : <div className="grid md:grid-cols-2 xl:grid-cols-3 gap-4">{query.data.map(source => {
    const Icon = source.source_type === 'network' ? Network : Database
    return <section key={source.source_type} className="stat-card"><div className="flex items-center justify-between mb-5"><span className="flex items-center gap-2 font-medium capitalize text-sm"><Icon size={17} className="text-accent"/>{sourceLabel(source.source_type)}</span><span className={`badge ${source.status==='active' ? 'bg-accent/10 text-accent' : source.status==='warning' ? 'bg-amber-500/10 text-amber-300' : 'bg-surface-700 text-slate-400'}`}>{!source.last_event ? 'No data' : source.status}</span></div><dl className="text-xs space-y-3"><div className="flex justify-between"><dt className="text-slate-500">Events per minute</dt><dd className="font-mono">{source.events_per_minute.toLocaleString()}</dd></div><div className="flex justify-between gap-2"><dt className="text-slate-500 shrink-0">Last event</dt><dd className="text-right">{source.last_event ? new Date(source.last_event).toLocaleString() : 'Not observed'}</dd></div></dl><p className="border-t border-surface-600/30 mt-5 pt-4 text-xs text-slate-400 leading-relaxed">{limitations[source.source_type] || 'Source-specific visibility depends on the connected upstream system.'}</p>{source.source_type === 'network' && <Link to="/network" className="inline-flex text-xs text-accent mt-4">Inspect network observations</Link>}</section>
  })}</div>}<a className="secondary-button" href="https://github.com/alebgl77/open-shadow-ai#quick-start" target="_blank" rel="noreferrer">Deployment & ingestion guide<ArrowUpRight size={14}/></a></div>
}
